# -*- coding: utf-8 -*-
"""Assignment 1.ipynb

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1_bKSjEDa4_KMNpan64nx8-Bc9LOXSn2J

# Problem 1
"""

def leap(year):
    if (year%4==0):
        if (year%100==0):
            if (year%400==0):
                return True
            else:
                return False
        else:
            return True
    else: 
        return False

year=1900
if (leap(year)):
    print("Leap year")
else:
    print("Not a leap year")

"""# Problem 2"""

def even(m):
    if m>=2 and m<=5:
        print("\nNot Weird")
    elif m>=6 and m<=20:
        print("\nWeird")
    else:
        print("\nNot Weird")

def check(m):
    if (m%2==0):
        print("Even")
        even(m)
    else: 
        print("Weird")

check(12)

"""# Problem 3

"""

A = ["Ram","Donald","Joe","Barrack","Narendra","Kim","Swatah","Matt","George"]
name=input("Enter who you wanna check is fashionable late: ")

for i in A:
  if (name.lower()==i.lower()):
    idx=A.index(i)
    check(idx)

def check(n):
  mid=len(A)/2
  last=len(A)-1
  if (n>=mid and n<last):
    print("Fashionably late")
  else:
    print("Not fashionably late")

"""# Problem 4

"""

List = ["This is an example of an Article.","This is another example.","Cases get closed very fast.","Examples are very efficient.", 
        "Not all example, yes.","This is without the key word.","This is just adding to the list.","Example this is with the key word."]
key=input("Enter the keyword: ")
for i in List:
  j=i.split()
  for m in j:
    if (m.lower()==key.lower()):
      print(i)
    elif (m.lower()==((key + '.').lower())) or (m.lower()==((key + ',').lower())):
      print(i)

"""# Problem 5

"""

BP=input("Enter your basic pay: ")
DA=0.40*float(BP)
HRA=0.20*float(BP)
GP=float(BP)+float(DA)+float(HRA)
print(GP)